# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
platform :ios do

  desc "build app and upload to TestFlight"

  lane :beta do
    get_certificates
    get_provisioning_profile
    cocoapods(use_bundle_exec: false)
    increment_build_number(
      build_number: latest_testflight_build_number + 1
    )
    build_app(
	    scheme: "Bogota"
    )
    pilot(
      api_key_path: "fastlane/3HTZ82WGNV.json",
      skip_waiting_for_build_processing: true
    )
    slack(
    message: "Testflight 배포에 성공했습니다!",
    slack_url: "https://hooks.slack.com/services/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"
    )
  end

  error do |lane, exception, options|
    slack(
      message: "에러 발생 : #{exception}",
      success: false,
      slack_url: "https://hooks.slack.com/services/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",
    )
  end

end